### PR TITLE
Fix mobile responsiveness

### PR DESCRIPTION
**Pull request by ruledio**
Fix mobile responsiveness and send button, had a gripe this morning that I couldn't send, I was missing the subject.

### CODE REVIEW

**Comment by cossssmin** [comment]
Thanks for this, it's now much better on mobile. 

Now that my assumption that people wouldn't really test HTML emails from a mobile device has been proven wrong, I wonder if we can make it even better. I'll play around with this to see if those fields can be better on mobile (maybe stacked); and also the panes, maybe...

**Comment by cossssmin** [comment]
Actually I'm just gonna merge this and see to it later, thanks again!

**Comment by ruledio** [comment]
I actually looked at the panes and switching them to vertical on mob, I managed to get this working but would only work on initial render, not resize of browsers and I wasn't happy with that so I reverted, maybe it is possible to listen to resize event and trigger orientation of the splitscreen.

**Comment by cossssmin** [comment]
Getting the viewport width and splitting based on that should be enough I think...

**Pull request merged**
